customhost = "database-1.ccshvphj0tcv.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "nelsonpcf-employee"
customregion = "us-east-1"
